run1:
	gcc A2Q1.c
	./a.out

run2:
	gcc A2Q2SinglyLL.c
	./a.out

run3:
	gcc A2Q2DoublyLL.c
	./a.out

run4:
	gcc A2Q2Stack.c
	./a.out

run5:
	gcc A2Q2Queue.c
	./a.out

run6:
	gcc A2Q3.c
	./a.out	

run7:
	gcc A2Q5.c
	./a.out